# Generated by Django 6.0 on 2025-12-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0002_schoolyear_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название (1-я Четверть)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата конца')),
                ('is_active', models.BooleanField(default=False, verbose_name='Текущая четверть')),
            ],
            options={
                'verbose_name': 'Четверть',
                'verbose_name_plural': 'Четверти',
                'ordering': ['start_date'],
            },
        ),
    ]
