# Generated by Django 6.0 on 2025-12-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0003_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='gat_exam.schoolyear', verbose_name='Учебный год'),
        ),
    ]
