# Generated by Django 6.0 on 2025-12-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0004_quarter_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Текущая эра'),
        ),
    ]
