# Generated by Django 6.0 on 2025-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0005_alter_schoolyear_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название школы')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальная ссылка (slug)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='Логотип')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email школы')),
                ('primary_color', models.CharField(default='#7c3aed', max_length=7, verbose_name='Основной цвет (HEX)')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
    ]
