# Generated by Django 6.0 on 2025-12-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0006_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], verbose_name='Параллель (цифра)')),
                ('section', models.CharField(max_length=5, verbose_name='Литера (А, Б, В...)')),
                ('language', models.CharField(blank=True, default='Русский', max_length=50, verbose_name='Язык обучения')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gat_exam.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['grade_level', 'section'],
                'unique_together': {('school', 'grade_level', 'section')},
            },
        ),
    ]
