# Generated by Django 6.0 on 2025-12-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0007_studentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='grade_level',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13')], verbose_name='Параллель'),
        ),
    ]
