# Generated by Django 6.0 on 2025-12-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0008_alter_studentclass_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_grade_level',
            field=models.PositiveIntegerField(default=11, verbose_name='Макс. класс'),
        ),
    ]
