# Generated by Django 6.0 on 2025-12-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0009_school_max_grade_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10, verbose_name='Пол')),
                ('status', models.CharField(choices=[('active', 'Учится'), ('graduated', 'Выпускник'), ('expelled', 'Отчислен')], default='active', max_length=20, verbose_name='Статус')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='gat_exam.school', verbose_name='Школа')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='gat_exam.studentclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
