# Generated by Django 6.0 on 2025-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0010_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='school_banners/', verbose_name='Обложка (Баннер)'),
        ),
        migrations.AddField(
            model_name='school',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код школы (ID)'),
        ),
    ]
