# Generated by Django 6.0 on 2025-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0011_school_banner_school_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='min_grade_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Мин. класс'),
        ),
    ]
