# Generated by Django 6.0 on 2025-12-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0012_school_min_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название школы'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='gat_exam_st_last_na_09f594_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='gat_exam_st_status_44f48b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school'], name='gat_exam_st_school__7ea4a8_idx'),
        ),
    ]
