# Generated by Django 6.0 on 2025-12-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Личного дела'),
        ),
    ]
