# Generated by Django 6.0 on 2025-12-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0015_student_custom_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name_ru', 'first_name_ru'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='gat_exam_st_last_na_09f594_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='gat_exam_st_status_44f48b_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='gat_exam_st_school__7ea4a8_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя (EN)'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_ru',
            field=models.CharField(default='', max_length=50, verbose_name='Имя (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_tj',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя (TJ)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия (EN)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_ru',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_tj',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия (TJ)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='custom_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID Личного дела'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
    ]
