# Generated by Django 6.0 on 2025-12-30 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0016_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('abbreviation', models.CharField(blank=True, max_length=10, verbose_name='Сокращение (МАТ)')),
                ('category', models.CharField(choices=[('Точные науки', 'Точные науки'), ('Естественные науки', 'Естественные науки'), ('Гуманитарные', 'Гуманитарные'), ('Языки', 'Языки'), ('Искусство', 'Искусство'), ('Спорт', 'Спорт'), ('Другое', 'Другое')], default='Точные науки', max_length=50, verbose_name='Категория')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Цвет (Slug)')),
                ('icon_type', models.CharField(default='default', max_length=20, verbose_name='Иконка (ID)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='gat_exam.subject', verbose_name='Предмет'),
        ),
    ]
