# Generated by Django 6.0 on 2025-12-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0017_subject_exam_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField(choices=[(1, '1-я Четверть'), (2, '2-я Четверть'), (3, '3-я Четверть'), (4, '4-я Четверть')], verbose_name='Четверть')),
                ('grade_level', models.PositiveIntegerField(help_text='Например: 10', verbose_name='Класс (Параллель)')),
                ('title', models.CharField(max_length=255, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='gat_exam.school', verbose_name='Школа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='gat_exam.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['grade_level', 'quarter', 'title'],
            },
        ),
    ]
