# Generated by Django 6.0 on 2025-12-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0019_alter_question_options_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Стандартный'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение'),
        ),
    ]
