# Generated by Django 6.0 on 2026-01-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0021_alter_choice_options_choice_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_audit_passed',
            field=models.BooleanField(default=False, verbose_name='Прошел AI аудит'),
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='emotional_check',
            field=models.BooleanField(default=False, verbose_name='Психо-замер'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('online', 'Online Exam'), ('offline', 'Offline (Paper)'), ('cambridge_ai', 'Cambridge AI')], default='online', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_adaptive',
            field=models.BooleanField(default=False, verbose_name='Адаптивный (CAT)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='lockdown_mode',
            field=models.BooleanField(default=False, verbose_name='Блокировка вкладок'),
        ),
        migrations.AddField(
            model_name='exam',
            name='smart_seating',
            field=models.BooleanField(default=False, verbose_name='Умная рассадка'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('grading', 'Grading (AI Work)'), ('finished', 'Finished')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='exam',
            name='variants_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во вариантов'),
        ),
        migrations.AddField(
            model_name='exam',
            name='webcam_monitoring',
            field=models.BooleanField(default=False, verbose_name='Веб-камера'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.PositiveIntegerField(default=60, help_text='Дублирует duration', verbose_name='Время (мин)'),
        ),
    ]
