# Generated by Django 6.0 on 2026-01-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0022_exam_ai_audit_passed_exam_date_exam_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GAT Premium Platform', max_length=100, verbose_name='Название платформы')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('tj', 'Тоҷикӣ'), ('en', 'English')], default='ru', max_length=10, verbose_name='Язык по умолчанию')),
                ('timezone', models.CharField(default='dushanbe', max_length=50, verbose_name='Часовой пояс')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Логотип')),
                ('current_year', models.CharField(default='2024-2025', max_length=20, verbose_name='Текущий учебный год')),
                ('grading_system', models.CharField(choices=[('100', '100-балльная'), ('5', '5-балльная'), ('letters', 'Буквенная')], default='100', max_length=20, verbose_name='Система оценивания')),
                ('pass_mark', models.IntegerField(default=60, verbose_name='Порог прохождения (%)')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Если включено, доступ только у админов', verbose_name='Режим обслуживания')),
                ('allow_registration', models.BooleanField(default=False, verbose_name='Разрешить регистрацию')),
                ('force_2fa', models.BooleanField(default=False, verbose_name='Принудительная 2FA для админов')),
                ('email_alerts', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=100, verbose_name='SMTP Host')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Telegram Token')),
                ('theme', models.CharField(default='light', max_length=10, verbose_name='Тема')),
                ('primary_color', models.CharField(default='indigo', max_length=20, verbose_name='Основной цвет')),
            ],
            options={
                'verbose_name': 'Настройки Системы',
                'verbose_name_plural': 'Настройки Системы',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Итоговый балл')),
                ('max_score', models.FloatField(verbose_name='Макс. балл')),
                ('percentage', models.FloatField(default=0, verbose_name='Процент')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали ответов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='gat_exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='gat_exam.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
