# Generated by Django 6.0 on 2026-01-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0024_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='homeroom_teachers', to='gat_exam.studentclass', verbose_name='Курируемые классы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_schools',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='gat_exam.school', verbose_name='Прикрепленные школы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_experts', to='gat_exam.subject', verbose_name='Курируемые предметы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_primary', to='gat_exam.school'),
        ),
    ]
