# Generated by Django 6.0 on 2026-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0025_userprofile_assigned_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('director', 'Директор'), ('deputy', 'Зам. директора'), ('expert', 'Эксперт/Методист'), ('teacher', 'Учитель'), ('homeroom', 'Классный руководитель')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
    ]
