# Generated by Django 6.0 on 2026-01-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0026_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Сокращение (МАТ)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('general_director', 'Ген. Директор'), ('director', 'Директор'), ('deputy', 'Зам. директора'), ('expert', 'Эксперт/Методист'), ('teacher', 'Учитель')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
    ]
