# Generated by Django 6.0 on 2026-01-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0027_alter_subject_abbreviation_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='classes',
            field=models.ManyToManyField(blank=True, to='gat_exam.studentclass', verbose_name='Классы'),
        ),
        migrations.AddField(
            model_name='exam',
            name='gat_day',
            field=models.IntegerField(choices=[(1, 'День 1'), (2, 'День 2')], default=1, verbose_name='День экзамена'),
        ),
        migrations.AddField(
            model_name='exam',
            name='gat_round',
            field=models.IntegerField(choices=[(1, 'GAT-1'), (2, 'GAT-2'), (3, 'GAT-3'), (4, 'GAT-4')], default=1, verbose_name='Номер GAT'),
        ),
        migrations.AddField(
            model_name='exam',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gat_exam.quarter', verbose_name='Четверть'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gat_exam.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('active', 'Идет экзамен'), ('grading', 'Идет проверка'), ('finished', 'Завершен')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
