# Generated by Django 6.0 on 2026-01-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0028_exam_classes_exam_gat_day_exam_gat_round_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exams', to='gat_exam.subject', verbose_name='Предметы'),
        ),
    ]
