# Generated by Django 6.0 on 2026-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0029_remove_exam_subject_exam_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='time_limit',
        ),
        migrations.AlterField(
            model_name='exam',
            name='ai_audit_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='emotional_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_adaptive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lockdown_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='smart_seating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='webcam_monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
