# Generated by Django 6.0 on 2026-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0030_remove_exam_time_limit_alter_exam_ai_audit_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (EN)'),
        ),
        migrations.AddField(
            model_name='school',
            name='address_tj',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (TJ)'),
        ),
        migrations.AddField(
            model_name='school',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='school',
            name='name_tj',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (TJ)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (RU)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название (RU)'),
        ),
    ]
