# Generated by Django 6.0 on 2026-01-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0031_school_address_en_school_address_tj_school_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['start_date'], 'verbose_name': 'Учебный год', 'verbose_name_plural': 'Учебные годы'},
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='name_tj',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название (TJ)'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Текущий год'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название (RU)'),
        ),
    ]
