# Generated by Django 6.0 on 2026-01-08 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0032_alter_schoolyear_options_schoolyear_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarter',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='quarter',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='name_tj',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название (TJ)'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='school_year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='gat_exam.schoolyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarter',
            name='start_date',
            field=models.DateField(),
        ),
    ]
