# Generated by Django 6.0 on 2026-01-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0033_alter_quarter_options_quarter_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='exams', to='gat_exam.studentclass', verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='gat_exam.school', verbose_name='Школа'),
        ),
    ]
