# Generated by Django 6.0 on 2026-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0034_alter_exam_classes_alter_exam_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_tj',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (TJ)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, verbose_name='Сокращение (МАТ)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название предмета (RU)'),
        ),
    ]
