# Generated by Django 6.0 on 2026-01-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0035_subject_name_en_subject_name_tj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='school',
        ),
        migrations.AddField(
            model_name='topic',
            name='schools',
            field=models.ManyToManyField(related_name='topics', to='gat_exam.school', verbose_name='Школы'),
        ),
    ]
