# Generated by Django 6.0 on 2026-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0036_remove_topic_school_topic_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий (1 балл)'), ('medium', 'Стандартный (2 балла)'), ('hard', 'Сложный (3 балла)')], default='medium', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных'), ('true_false', 'Истина / Ложь'), ('short_answer', 'Краткий ответ'), ('essay', 'Эссе (Развернутый ответ)'), ('blanks', 'Заполнение пропусков'), ('matching', 'Сопоставление'), ('ordering', 'Сортировка')], default='single', max_length=20, verbose_name='Тип'),
        ),
    ]
