# Generated by Django 6.0 on 2026-01-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0037_alter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Уникальная ссылка (slug)'),
        ),
    ]
