# Generated by Django 6.0 on 2026-01-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0038_alter_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.CharField(choices=[('A', 'Вариант A'), ('B', 'Вариант B'), ('C', 'Вариант C'), ('D', 'Вариант D'), ('All', 'Для всех вариантов')], default='All', max_length=5, verbose_name='Вариант'),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Код (slug)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Стандартный'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность'),
        ),
    ]
