# Generated by Django 6.0 on 2026-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0039_question_points_question_variant_subject_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', unique=True, verbose_name='Код (slug)'),
            preserve_default=False,
        ),
    ]
