# Generated by Django 6.0 on 2026-01-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0040_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='color_theme',
            field=models.CharField(choices=[('emerald', 'Emerald (Зеленый)'), ('blue', 'Blue (Синий)'), ('violet', 'Violet (Фиолетовый)'), ('amber', 'Amber (Оранжевый)'), ('rose', 'Rose (Розовый)'), ('cyan', 'Cyan (Голубой)')], default='blue', max_length=20, verbose_name='Цветовая тема (для сайта)'),
        ),
    ]
