# Generated by Django 6.0 on 2026-01-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gat_exam', '0041_school_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Код школы (ID)'),
        ),
    ]
